CREATE TABLE ALUMNO (ID NUMBER GENERATED ALWAYS AS IDENTITY, NOMBRE VARCHAR2(60) NOT NULL, CONSTRAINT PK_ALUMNO PRIMARY KEY(ID));
ALTER TABLE ALUMNO ADD EMAIL VARCHAR2(120) UNIQUE;
COMMENT ON COLUMN ALUMNO.EMAIL IS 'Email único';
-- TRUNCATE borra rápido (sin WHERE) e irreversible
TRUNCATE TABLE ALUMNO;
