-- =========================
-- 🧱 ESQUEMA DE EJEMPLO
-- =========================
DROP TABLE LINEA_PEDIDO CASCADE CONSTRAINTS PURGE;
DROP TABLE PEDIDO       CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTE      CASCADE CONSTRAINTS PURGE;

CREATE TABLE CLIENTE (
  ID_CLIENTE    NUMBER GENERATED ALWAYS AS IDENTITY,
  NIF           VARCHAR2(15)   NOT NULL,
  NOMBRE        VARCHAR2(80)   NOT NULL,
  EMAIL         VARCHAR2(120)  UNIQUE,
  F_ALTA        DATE           DEFAULT SYSDATE NOT NULL,
  ID_REFERIDOR  NUMBER,  -- self-FK para ejemplo de SELF JOIN (opcional)
  CONSTRAINT PK_CLIENTE         PRIMARY KEY (ID_CLIENTE),
  CONSTRAINT UQ_CLIENTE_NIF     UNIQUE (NIF),
  CONSTRAINT CK_CLIENTE_NIF     CHECK (REGEXP_LIKE(NIF,'^[0-9A-Z]{8,15}$'))
);

ALTER TABLE CLIENTE
  ADD CONSTRAINT FK_CLIENTE_REF
  FOREIGN KEY (ID_REFERIDOR) REFERENCES CLIENTE(ID_CLIENTE);

CREATE TABLE PEDIDO (
  ID_PEDIDO   NUMBER GENERATED ALWAYS AS IDENTITY,
  ID_CLIENTE  NUMBER        NOT NULL,
  FECHA       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  ESTADO      VARCHAR2(20)  DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PENDIENTE','ENVIADO','CANCELADO')),
  IMPORTE     NUMBER(10,2)  DEFAULT 0 CHECK (IMPORTE >= 0),
  CONSTRAINT PK_PEDIDO          PRIMARY KEY (ID_PEDIDO),
  CONSTRAINT FK_PEDIDO_CLIENTE  FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE LINEA_PEDIDO (
  ID_LINEA   NUMBER GENERATED ALWAYS AS IDENTITY,
  ID_PEDIDO  NUMBER       NOT NULL,
  SKU        VARCHAR2(30) NOT NULL,
  CANTIDAD   NUMBER(6)    DEFAULT 1 CHECK (CANTIDAD > 0),
  PRECIO     NUMBER(10,2) NOT NULL CHECK (PRECIO >= 0),
  CONSTRAINT PK_LINEA           PRIMARY KEY (ID_LINEA),
  CONSTRAINT UQ_LINEA_UNICA     UNIQUE (ID_PEDIDO, SKU),
  CONSTRAINT FK_LINEA_PEDIDO    FOREIGN KEY (ID_PEDIDO)
    REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE
);

-- 👉 Índices recomendados para FKs (aceleran joins/borrados)
CREATE INDEX IX_PEDIDO_ID_CLIENTE ON PEDIDO(ID_CLIENTE);
CREATE INDEX IX_LINEA_ID_PEDIDO   ON LINEA_PEDIDO(ID_PEDIDO);

-- Documentación
COMMENT ON TABLE CLIENTE IS 'Clientes';
COMMENT ON COLUMN PEDIDO.ESTADO IS 'PENDIENTE|ENVIADO|CANCELADO';

-- Semillas mínimas (opcionales)
INSERT INTO CLIENTE(NIF,NOMBRE,EMAIL) VALUES ('00000000A','Ana','ana@acme.es');
INSERT INTO CLIENTE(NIF,NOMBRE)       VALUES ('00000000B','Cris');
INSERT INTO PEDIDO(ID_CLIENTE,ESTADO,IMPORTE) SELECT ID_CLIENTE,'ENVIADO',39.9 FROM CLIENTE WHERE NIF='00000000A';
INSERT INTO LINEA_PEDIDO(ID_PEDIDO,SKU,CANTIDAD,PRECIO)
  SELECT p.ID_PEDIDO,'CUADERNO-A5',2,9.95 FROM PEDIDO p FETCH FIRST 1 ROWS ONLY;
COMMIT;

-- =========================
-- 🛠️ DDL frecuentes (plantilla)
-- =========================
-- Añadir columna
ALTER TABLE CLIENTE ADD TELEFONO VARCHAR2(20);

-- Cambiar tipo/longitud (si no rompe datos)
ALTER TABLE CLIENTE MODIFY TELEFONO VARCHAR2(30);

-- Eliminar columna
ALTER TABLE CLIENTE DROP COLUMN TELEFONO;

-- Añadir/retocar restricciones
ALTER TABLE PEDIDO ADD CONSTRAINT CK_PEDIDO_IMPORTE CHECK (IMPORTE >= 0);
ALTER TABLE PEDIDO DROP CONSTRAINT CK_PEDIDO_IMPORTE;

-- Vaciar tabla rápido (irreversible, no dispara triggers por fila)
TRUNCATE TABLE LINEA_PEDIDO;

-- Borrado lógico recomendado: usa columna ESTADO/ACTIVO en vez de DELETE si necesitas histórico.
