INSERT INTO ALUMNO (NOMBRE) VALUES ('Ana');
UPDATE ALUMNO SET NOMBRE='Ana Arroyo' WHERE ID=1;
DELETE FROM ALUMNO WHERE ID=1;
MERGE INTO CURSO c
USING (SELECT 'SQL1' CODIGO, 'SQL Básico' NOMBRE, 5 CREDITOS FROM DUAL) src
ON (c.CODIGO=src.CODIGO)
WHEN MATCHED THEN UPDATE SET c.NOMBRE=src.NOMBRE, c.CREDITOS=src.CREDITOS
WHEN NOT MATCHED THEN INSERT (CODIGO,NOMBRE,CREDITOS) VALUES (src.CODIGO,src.NOMBRE,src.CREDITOS);
