SELECT ID, NOMBRE
FROM   ALUMNO
WHERE  UPPER(NOMBRE)=UPPER('ana')
ORDER  BY NOMBRE;

-- Agregación + filtro de grupos
SELECT ID_CURSO, ROUND(AVG(NOTA_FINAL),2) AS MEDIA
FROM   MATRICULA
GROUP  BY ID_CURSO
HAVING AVG(NOTA_FINAL) >= 5;
